displayName: Enforce Header Case
type: middleware
iconPath: .assets/icon.png

import: github.com/swtch-energy/traefik-enforce-header-case-plugin

summary: 'Enforces the case of specified request and response headers.'

testData:
  Headers:
    - x-tEsT-hEAder
